name=MultiServo
version=1.0.0
author=AlexGyver <alex@alexgyver.ru>
maintainer=AlexGyver <alex@alexgyver.ru>
sentence=Library for controlling multichannel servo drivers like PCA9685
paragraph=Library for controlling multichannel servo drivers like PCA9685
category=Device Control
url=https://github.com/GyverLibs/MultiServo
architectures=*